version: '2'
services:
  apache:
    build: ./docker/apache/.
    volumes:
      - .:/var/www/code
    working_dir: /var/www/code
    ports:
      - "9000:80"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
      DEBUG: 'true'
      TEST_MODE: 'local'
      DB_HOST: db
      DB_DATABASE: project
      DB_USERNAME: project
      DB_PASSWORD: project
      DB_PORT: 3306
    links:
      - db
  db:
    build: ./docker/mysql/.
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: project
      MYSQL_PASSWORD: project
      MYSQL_DATABASE: project
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - "3311:3306"
    command: mysqld --sql_mode=""
  node:
    build: ./docker/node/.
    working_dir: /app
    volumes:
      - .:/app
    links:
      - apache
    command: bash -c "ln -sf /node_modules node_modules && sleep infinity"
    ports:
      - "3000:3000"
volumes:
  esdata1:
    driver: local